static const char* const TokenKinds_repr[] = {
    [tkNullChar] = "EOF",
    [tkKeyword_for] = "for",
    [tkKeyword_while] = "while",
    [tkKeyword_if] = "if",
    [tkKeyword_match] = "match",
    [tkKeyword_case] = "case",
    [tkKeyword_else] = "else",
    [tkKeyword_elif] = "else if",
    [tkKeyword_do] = " do ",
    [tkKeyword_then] = " then ",
    [tkKeyword_end] = "end",
    [tkKeyword_enum] = "enum",
    [tkKeyword_function] = "function",
    [tkKeyword_declare] = "declare",
    [tkKeyword_test] = "test",
    [tkKeyword_check] = "check",
    [tkKeyword_not] = "not ",
    [tkKeyword_and] = " and ",
    [tkKeyword_or] = " or ",
    [tkKeyword_in] = " in ",
    [tkKeyword_notin] = " not in ",
    [tkKeyword_yes] = "yes",
    [tkKeyword_no] = "no",
    [tkKeyword_nil] = "nil",
    [tkKeyword_as] = " as ",
    [tkKeyword_type] = "type ",
    [tkKeyword_return] = "return ",
    [tkKeyword_result] = " result ",
    [tkKeyword_extends] = " extends ",
    [tkKeyword_var] = "var ",
    [tkKeyword_let] = "let ",
    [tkKeyword_import] = "import ",
    [tkIdentifier] = "(id)",
    [tkArgumentLabel] = "(lbl)",
    [tkFunctionCall] = "(call)",
    [tkSubscript] = "(sub)",
    [tkObjectInit] = "(obj)",
    [tkNumber] = "'123'",
    [tkIdentifierResolved] = "[id]",
    [tkFunctionCallResolved] = "[call]",
    [tkSubscriptResolved] = "[sub]",
    [tkObjectInitResolved] = "{obj}",
    [tkNumberAsInt] = "123",
    [tkNumberAsDbl] = "1.23",
    [tkNumberAsUInt] = "+123",
    [tkMultiDotNumber] = "1.2.3",
    [tkSpaces] = "(spc)",
    [tkOneSpace] = "(sp1)",
    [tkTab] = "(tab)",
    [tkNewline] = "(nl)",
    [tkLineComment] = "#",
    [tkAlphabet] = "a",
    [tkAmpersand] = "&",
    [tkArrayClose] = "]",
    [tkArrayOpen] = "[",
    [tkArrayDims] = "[:]",
    [tkAt] = "@",
    [tkBraceClose] = "}",
    [tkBraceOpen] = "{",
    [tkDigit] = "1",
    [tkHash] = "#",
    [tkUnaryDot] = ".",
    [tkExclamation] = "!",
    [tkPipe] = "|",
    [tkOpAssign] = "=",
    [tkVarAssign] = "v=",
    [tkOpEQ] = "==",
    [tkOpNE] = "!=",
    [tkOpGE] = ">=",
    [tkOpGT] = ">",
    [tkOpLE] = "<=",
    [tkOpLT] = "<",
    [tkOpResults] = " -> ",
    [tkOpNotResults] = " -/> ",
    [tkParenClose] = ")",
    [tkParenOpen] = "(",
    [tkPeriod] = ".",
    [tkOpComma] = ", ",
    [tkOpSemiColon] = "; ",
    [tkOpColon] = ":",
    [tkStringBoundary] = "\"",
    [tkString] = "\"abc\"",
    [tkRawStringBoundary] = "'",
    [tkRawString] = "'abc'",
    [tkRegexpBoundary] = "`",
    [tkRegexp] = "`abc`",
    [tkUnderscore] = "_",
    [tkOpSlash] = "/",
    [tkOpBackslash] = "\\",
    [tkOpPlus] = "+",
    [tkOpMinus] = "-",
    [tkOpUnaryMinus] = "-",
    [tkOpTimes] = "*",
    [tkOpPower] = "^",
    [tkOpPowerEq] = " ^= ",
    [tkOpMod] = "%",
    [tkTilde] = "~",
    [tkDollar] = "$",
    [tkUnits] = "|N.m/s",
    [tkOpPlusEq] = " += ",
    [tkOpMinusEq] = " -= ",
    [tkOpSlashEq] = " /= ",
    [tkOpTimesEq] = " *= ",
    [tkOpColEq] = " := ",
    [tkOpModEq] = " %= ",
    [tkOpQuestion] = "?",
    [tkUnknown] = "(unk)",
};

