dist: focal
os:
  - linux
  - windows
  - osx
arch:
  - amd64
  - arm64
language: c

jobs:
  include:
    - stage: build
      script: make
    - stage: test
      script: make test

stages:
  - build
  - test
