 local tk = {
    NullChar = {id=1, name="NullChar", repr="EOF"}, 
    __tk__keywords__begin = {id=2, name="__tk__keywords__begin", repr=""}, 
    __tk__ctrlflow__begin = {id=3, name="__tk__ctrlflow__begin", repr=""}, 
    Keyword_for = {id=4, name="Keyword_for", repr="for "}, 
    Keyword_while = {id=5, name="Keyword_while", repr="while "}, 
    Keyword_if = {id=6, name="Keyword_if", repr="if "}, 
    Keyword_match = {id=7, name="Keyword_match", repr="match "}, 
    Keyword_case = {id=8, name="Keyword_case", repr="case "}, 
    Keyword_else = {id=9, name="Keyword_else", repr="else"}, 
    Keyword_elif = {id=10, name="Keyword_elif", repr="else if "}, 
    Keyword_do = {id=11, name="Keyword_do", repr=" do "}, 
    Keyword_then = {id=12, name="Keyword_then", repr=" then "}, 
    __tk__ctrlflow__end = {id=13, name="__tk__ctrlflow__end", repr=""}, 
    Keyword_end = {id=14, name="Keyword_end", repr="end"}, 
    Keyword_enum = {id=15, name="Keyword_enum", repr="enum "}, 
    Keyword_function = {id=16, name="Keyword_function", repr="function"}, 
    Keyword_declare = {id=17, name="Keyword_declare", repr="declare"}, 
    Keyword_test = {id=18, name="Keyword_test", repr="test "}, 
    Keyword_check = {id=19, name="Keyword_check", repr="check "}, 
    __tk__logicals__begin = {id=20, name="__tk__logicals__begin", repr=""}, 
    Keyword_not = {id=21, name="Keyword_not", repr="not "}, 
    Keyword_and = {id=22, name="Keyword_and", repr=" and "}, 
    Keyword_or = {id=23, name="Keyword_or", repr=" or "}, 
    Keyword_in = {id=24, name="Keyword_in", repr=" in "}, 
    Keyword_notin = {id=25, name="Keyword_notin", repr=" not in "}, 
    __tk__logicals__end = {id=26, name="__tk__logicals__end", repr=""}, 
    Keyword_yes = {id=27, name="Keyword_yes", repr="yes"}, 
    Keyword_no = {id=28, name="Keyword_no", repr="no"}, 
    Keyword_nil = {id=29, name="Keyword_nil", repr="nil"}, 
    Keyword_as = {id=30, name="Keyword_as", repr=" as "}, 
    Keyword_type = {id=31, name="Keyword_type", repr="type "}, 
    Keyword_return = {id=32, name="Keyword_return", repr="return "}, 
    Keyword_result = {id=33, name="Keyword_result", repr=" result "}, 
    Keyword_extends = {id=34, name="Keyword_extends", repr=" extends "}, 
    Keyword_var = {id=35, name="Keyword_var", repr="var "}, 
    Keyword_let = {id=36, name="Keyword_let", repr="let "}, 
    Keyword_import = {id=37, name="Keyword_import", repr="import "}, 
    __tk__keywords__end = {id=38, name="__tk__keywords__end", repr=""}, 
    Identifier = {id=39, name="Identifier", repr="(id)"}, 
    ArgumentLabel = {id=40, name="ArgumentLabel", repr="(lbl)"}, 
    FunctionCall = {id=41, name="FunctionCall", repr="(call)"}, 
    Subscript = {id=42, name="Subscript", repr="(sub)"}, 
    ObjectInit = {id=43, name="ObjectInit", repr="(obj)"}, 
    Number = {id=44, name="Number", repr="'123'"}, 
    IdentifierResolved = {id=45, name="IdentifierResolved", repr="[id]"}, 
    FunctionCallResolved = {id=46, name="FunctionCallResolved", repr="[call]"}, 
    SubscriptResolved = {id=47, name="SubscriptResolved", repr="[sub]"}, 
    ObjectInitResolved = {id=48, name="ObjectInitResolved", repr="{obj}"}, 
    NumberAsInt = {id=49, name="NumberAsInt", repr="123"}, 
    NumberAsDbl = {id=50, name="NumberAsDbl", repr="1.23"}, 
    NumberAsUInt = {id=51, name="NumberAsUInt", repr="+123"}, 
    MultiDotNumber = {id=52, name="MultiDotNumber", repr="1.2.3"}, 
    Spaces = {id=53, name="Spaces", repr="(spc)"}, 
    OneSpace = {id=54, name="OneSpace", repr="(sp1)"}, 
    Tab = {id=55, name="Tab", repr="(tab)"}, 
    Newline = {id=56, name="Newline", repr="(nl)"}, 
    LineComment = {id=57, name="LineComment", repr="#"}, 
    Alphabet = {id=58, name="Alphabet", repr="a"}, 
    Ampersand = {id=59, name="Ampersand", repr="&"}, 
    ArrayClose = {id=60, name="ArrayClose", repr="]"}, 
    ArrayOpen = {id=61, name="ArrayOpen", repr="["}, 
    ArrayDims = {id=62, name="ArrayDims", repr="[:]"}, 
    At = {id=63, name="At", repr="@"}, 
    BraceClose = {id=64, name="BraceClose", repr="}"}, 
    BraceOpen = {id=65, name="BraceOpen", repr="{"}, 
    Digit = {id=66, name="Digit", repr="1"}, 
    Hash = {id=67, name="Hash", repr="#"}, 
    UnaryDot = {id=68, name="UnaryDot", repr="."}, 
    Exclamation = {id=69, name="Exclamation", repr="!"}, 
    Pipe = {id=70, name="Pipe", repr="|"}, 
    OpAssign = {id=71, name="OpAssign", repr=" = "}, 
    VarAssign = {id=72, name="VarAssign", repr="v="}, 
    __tk__cmpOps__begin = {id=73, name="__tk__cmpOps__begin", repr=""}, 
    OpEQ = {id=74, name="OpEQ", repr=" == "}, 
    OpNE = {id=75, name="OpNE", repr=" != "}, 
    OpGE = {id=76, name="OpGE", repr=" >= "}, 
    OpGT = {id=77, name="OpGT", repr=" > "}, 
    OpLE = {id=78, name="OpLE", repr=" <= "}, 
    OpLT = {id=79, name="OpLT", repr=" < "}, 
    __tk__cmpOps__end = {id=80, name="__tk__cmpOps__end", repr=""}, 
    OpResults = {id=81, name="OpResults", repr=" -> "}, 
    OpNotResults = {id=82, name="OpNotResults", repr=" -/> "}, 
    ParenClose = {id=83, name="ParenClose", repr=")"}, 
    ParenOpen = {id=84, name="ParenOpen", repr="("}, 
    Period = {id=85, name="Period", repr="."}, 
    OpComma = {id=86, name="OpComma", repr=", "}, 
    OpSemiColon = {id=87, name="OpSemiColon", repr="; "}, 
    OpColon = {id=88, name="OpColon", repr=":"}, 
    StringBoundary = {id=89, name="StringBoundary", repr="\""}, 
    String = {id=90, name="String", repr="\"abc\""}, 
    RawStringBoundary = {id=91, name="RawStringBoundary", repr="'"}, 
    RawString = {id=92, name="RawString", repr="'abc'"}, 
    RegexpBoundary = {id=93, name="RegexpBoundary", repr="`"}, 
    Regexp = {id=94, name="Regexp", repr="`abc`"}, 
    Underscore = {id=95, name="Underscore", repr="_"}, 
    __tk__arithOps__begin = {id=96, name="__tk__arithOps__begin", repr=""}, 
    OpSlash = {id=97, name="OpSlash", repr=" / "}, 
    OpBackslash = {id=98, name="OpBackslash", repr=" \\ "}, 
    OpPlus = {id=99, name="OpPlus", repr=" + "}, 
    OpMinus = {id=100, name="OpMinus", repr=" - "}, 
    OpUnaryMinus = {id=101, name="OpUnaryMinus", repr=" -"}, 
    OpTimes = {id=102, name="OpTimes", repr=" * "}, 
    OpPower = {id=103, name="OpPower", repr="^"}, 
    OpPowerEq = {id=104, name="OpPowerEq", repr=" ^= "}, 
    OpMod = {id=105, name="OpMod", repr=" % "}, 
    __tk__arithOps__end = {id=106, name="__tk__arithOps__end", repr=""}, 
    Tilde = {id=107, name="Tilde", repr="~"}, 
    Dollar = {id=108, name="Dollar", repr="$"}, 
    Units = {id=109, name="Units", repr="|N.m/s"}, 
    __tk__selfMutOps__begin = {id=110, name="__tk__selfMutOps__begin", repr=""}, 
    OpPlusEq = {id=111, name="OpPlusEq", repr=" += "}, 
    OpMinusEq = {id=112, name="OpMinusEq", repr=" -= "}, 
    OpSlashEq = {id=113, name="OpSlashEq", repr=" /= "}, 
    OpTimesEq = {id=114, name="OpTimesEq", repr=" *= "}, 
    OpColEq = {id=115, name="OpColEq", repr=" := "}, 
    OpModEq = {id=116, name="OpModEq", repr=" %= "}, 
    __tk__selfMutOps__end = {id=117, name="__tk__selfMutOps__end", repr=""}, 
    OpQuestion = {id=118, name="OpQuestion", repr="?"}, 
    Unknown = {id=119, name="Unknown", repr="(unk)"}, 
}
return tk

