 local tk = {
    EOF = {id=1, name="EOF", repr="EOF"}, 
    __tk__keywords__begin = {id=2, name="__tk__keywords__begin", repr=""}, 
    __tk__ctrlflow__begin = {id=3, name="__tk__ctrlflow__begin", repr=""}, 
    For = {id=4, name="For", repr="for "}, 
    While = {id=5, name="While", repr="while "}, 
    If = {id=6, name="If", repr="if "}, 
    Match = {id=7, name="Match", repr="match "}, 
    Case = {id=8, name="Case", repr="case "}, 
    Else = {id=9, name="Else", repr="else"}, 
    Elif = {id=10, name="Elif", repr="else if "}, 
    Do = {id=11, name="Do", repr=" do "}, 
    Then = {id=12, name="Then", repr=" then "}, 
    __tk__ctrlflow__end = {id=13, name="__tk__ctrlflow__end", repr=""}, 
    End = {id=14, name="End", repr="end"}, 
    Enum = {id=15, name="Enum", repr="enum "}, 
    Func = {id=16, name="Func", repr="func"}, 
    Decl = {id=17, name="Decl", repr="decl"}, 
    Test = {id=18, name="Test", repr="test "}, 
    Check = {id=19, name="Check", repr="check "}, 
    __tk__logicals__begin = {id=20, name="__tk__logicals__begin", repr=""}, 
    Not = {id=21, name="Not", repr="not "}, 
    And = {id=22, name="And", repr=" and "}, 
    Or = {id=23, name="Or", repr=" or "}, 
    In = {id=24, name="In", repr=" in "}, 
    Notin = {id=25, name="Notin", repr=" not in "}, 
    __tk__logicals__end = {id=26, name="__tk__logicals__end", repr=""}, 
    Yes = {id=27, name="Yes", repr="yes"}, 
    No = {id=28, name="No", repr="no"}, 
    Nil = {id=29, name="Nil", repr="nil"}, 
    As = {id=30, name="As", repr=" as "}, 
    Type = {id=31, name="Type", repr="type "}, 
    Return = {id=32, name="Return", repr="return "}, 
    Result = {id=33, name="Result", repr=" result "}, 
    Extends = {id=34, name="Extends", repr=" extends "}, 
    Var = {id=35, name="Var", repr="var "}, 
    Let = {id=36, name="Let", repr="let "}, 
    Import = {id=37, name="Import", repr="import "}, 
    __tk__keywords__end = {id=38, name="__tk__keywords__end", repr=""}, 
    Ident = {id=39, name="Ident", repr="(id)"}, 
    FuncCall = {id=40, name="FuncCall", repr="(call)"}, 
    Subscript = {id=41, name="Subscript", repr="(sub)"}, 
    ObjInit = {id=42, name="ObjInit", repr="(obj)"}, 
    Number = {id=43, name="Number", repr="'123'"}, 
    IdentR = {id=44, name="IdentR", repr="[id]"}, 
    FuncCallR = {id=45, name="FuncCallR", repr="[call]"}, 
    SubscriptR = {id=46, name="SubscriptR", repr="[sub]"}, 
    ObjInitR = {id=47, name="ObjInitR", repr="{obj}"}, 
    Spaces = {id=48, name="Spaces", repr="(spc)"}, 
    OneSpace = {id=49, name="OneSpace", repr="(sp1)"}, 
    Tab = {id=50, name="Tab", repr="(tab)"}, 
    EOL = {id=51, name="EOL", repr="(nl)"}, 
    Comment = {id=52, name="Comment", repr="#"}, 
    Alphabet = {id=53, name="Alphabet", repr="a"}, 
    Ampersand = {id=54, name="Ampersand", repr="&"}, 
    ArrayClose = {id=55, name="ArrayClose", repr="]"}, 
    ArrayOpen = {id=56, name="ArrayOpen", repr="["}, 
    ArrayDims = {id=57, name="ArrayDims", repr="[:]"}, 
    At = {id=58, name="At", repr="@"}, 
    BraceClose = {id=59, name="BraceClose", repr="}"}, 
    BraceOpen = {id=60, name="BraceOpen", repr="{"}, 
    Digit = {id=61, name="Digit", repr="1"}, 
    Hash = {id=62, name="Hash", repr="#"}, 
    UnaryDot = {id=63, name="UnaryDot", repr="."}, 
    Excl = {id=64, name="Excl", repr="!"}, 
    Pipe = {id=65, name="Pipe", repr="|"}, 
    Assign = {id=66, name="Assign", repr=" = "}, 
    VarDefn = {id=67, name="VarDefn", repr="v="}, 
    __tk__cmpOps__begin = {id=68, name="__tk__cmpOps__begin", repr=""}, 
    OpEQ = {id=69, name="OpEQ", repr=" == "}, 
    OpNE = {id=70, name="OpNE", repr=" != "}, 
    OpGE = {id=71, name="OpGE", repr=" >= "}, 
    OpGT = {id=72, name="OpGT", repr=" > "}, 
    OpLE = {id=73, name="OpLE", repr=" <= "}, 
    OpLT = {id=74, name="OpLT", repr=" < "}, 
    __tk__cmpOps__end = {id=75, name="__tk__cmpOps__end", repr=""}, 
    ParenClose = {id=76, name="ParenClose", repr=")"}, 
    ParenOpen = {id=77, name="ParenOpen", repr="("}, 
    Period = {id=78, name="Period", repr="."}, 
    OpComma = {id=79, name="OpComma", repr=", "}, 
    OpSemiColon = {id=80, name="OpSemiColon", repr="; "}, 
    OpColon = {id=81, name="OpColon", repr=":"}, 
    StringBoundary = {id=82, name="StringBoundary", repr="\""}, 
    String = {id=83, name="String", repr="\"abc\""}, 
    RawStringBoundary = {id=84, name="RawStringBoundary", repr="'"}, 
    RawString = {id=85, name="RawString", repr="'abc'"}, 
    RegexpBoundary = {id=86, name="RegexpBoundary", repr="`"}, 
    Regexp = {id=87, name="Regexp", repr="`abc`"}, 
    Underscore = {id=88, name="Underscore", repr="_"}, 
    __tk__arithOps__begin = {id=89, name="__tk__arithOps__begin", repr=""}, 
    OpSlash = {id=90, name="OpSlash", repr=" / "}, 
    OpBackslash = {id=91, name="OpBackslash", repr=" \\ "}, 
    OpPlus = {id=92, name="OpPlus", repr=" + "}, 
    OpMinus = {id=93, name="OpMinus", repr=" - "}, 
    OpUnaryMinus = {id=94, name="OpUnaryMinus", repr=" -"}, 
    OpTimes = {id=95, name="OpTimes", repr=" * "}, 
    OpPower = {id=96, name="OpPower", repr="^"}, 
    OpPowerEq = {id=97, name="OpPowerEq", repr=" ^= "}, 
    OpMod = {id=98, name="OpMod", repr=" % "}, 
    __tk__arithOps__end = {id=99, name="__tk__arithOps__end", repr=""}, 
    Tilde = {id=100, name="Tilde", repr="~"}, 
    Dollar = {id=101, name="Dollar", repr="$"}, 
    Units = {id=102, name="Units", repr="|N.m/s"}, 
    __tk__selfMutOps__begin = {id=103, name="__tk__selfMutOps__begin", repr=""}, 
    OpPlusEq = {id=104, name="OpPlusEq", repr=" += "}, 
    OpMinusEq = {id=105, name="OpMinusEq", repr=" -= "}, 
    OpSlashEq = {id=106, name="OpSlashEq", repr=" /= "}, 
    OpTimesEq = {id=107, name="OpTimesEq", repr=" *= "}, 
    OpColEq = {id=108, name="OpColEq", repr=" := "}, 
    OpModEq = {id=109, name="OpModEq", repr=" %= "}, 
    __tk__selfMutOps__end = {id=110, name="__tk__selfMutOps__end", repr=""}, 
    OpQuestion = {id=111, name="OpQuestion", repr="?"}, 
    Unknown = {id=112, name="Unknown", repr="(unk)"}, 
}
return tk

